"""Extracted mixin — part of inno3d.features.viewer refactor.

This module is auto-generated by scripts/extract_viewer_mixins.py.
Do NOT edit manually; edit viewer.py then re-run the script.

Layer: features/viewer (imports Qt, VTK — not for domain/infra use).
"""
from __future__ import annotations
# Qt / VTK imports are inherited from the host class at runtime.
# This mixin uses only `self.*` — no standalone imports needed here.


class MprNavMixin:
    """Mixin providing MprNav behaviour for MultiPlanarView.

    All methods use ``self.*`` attributes owned by MultiPlanarView.
    Do not instantiate directly.
    """
    def _active_mpr_orientation(self):
        ori = getattr(self, "_active_grid_pane", None)
        if ori in ("axial", "coronal", "sagittal"):
            return ori
        return "axial"


    def _ensure_crosshair_visible(self, orientation):
        """Auto-pan the 2D camera so the crosshair is visible in the viewport.

        Only activates when the user has zoomed-in (parallelScale < 85 % of
        the fit-to-view default).  At default zoom the entire image fits in
        the viewport, so the crosshair is always visible — no pan needed.
        """
        if self.volume_data is None:
            return

        renderer = getattr(self, f'{orientation}_renderer', None)
        if renderer is None:
            return
        camera = renderer.GetActiveCamera()
        if not camera.GetParallelProjection():
            return

        vol_z, vol_y, vol_x = self.volume_data.shape

        # Image dimensions for this orientation (same as render_slice)
        if orientation == 'axial':
            h, w = vol_y, vol_x
        elif orientation == 'coronal':
            h, w = vol_z, vol_x
        else:  # sagittal
            h, w = vol_y, vol_z

        # Compute the "fit-to-view" default parallel scale
        vtk_widget = getattr(self, f'{orientation}_widget')
        vp_size = vtk_widget.GetRenderWindow().GetSize()
        vp_w_px = max(vp_size[0], 1)
        vp_h_px = max(vp_size[1], 1)
        vp_aspect = vp_w_px / vp_h_px
        img_aspect = w / max(h, 1)

        if img_aspect > vp_aspect:
            default_scale = (w / vp_aspect) * 0.5
        else:
            default_scale = h * 0.5

        # Only auto-pan if the user has zoomed in significantly
        current_scale = camera.GetParallelScale()
        if current_scale > default_scale * 0.85:
            return  # Not zoomed in — crosshair is always visible

        # Determine the crosshair world-space position for this orientation
        if orientation == 'axial':
            cx_w = float(self.crosshair_position[0])
            cy_w = float(self.crosshair_position[1])
        elif orientation == 'coronal':
            cx_w = float(self.crosshair_position[0])
            cy_w = float((vol_z - 1) - self.crosshair_position[2])
        else:  # sagittal
            cx_w = float(self.crosshair_position[2])
            cy_w = float(self.crosshair_position[1])

        # Convert crosshair world coords → display coords
        coord = vtk.vtkCoordinate()
        coord.SetCoordinateSystemToWorld()
        coord.SetValue(cx_w, cy_w, 0.0)
        dp = coord.GetComputedDisplayValue(renderer)
        dx, dy = dp[0], dp[1]

        # Viewport pixel dimensions
        vp = renderer.GetViewport()
        vp_x0 = vp[0] * vp_size[0]
        vp_y0 = vp[1] * vp_size[1]
        vp_w = (vp[2] - vp[0]) * vp_size[0]
        vp_h = (vp[3] - vp[1]) * vp_size[1]

        # Check if crosshair display position is within the viewport
        # (no margin — only pan when truly off-screen)
        in_view = (
            vp_x0 <= dx <= (vp_x0 + vp_w) and
            vp_y0 <= dy <= (vp_y0 + vp_h)
        )

        if in_view:
            return  # Crosshair is visible — nothing to do

        # Pan camera to center on the crosshair world position
        pos = list(camera.GetPosition())
        fp = list(camera.GetFocalPoint())

        delta_x = cx_w - fp[0]
        delta_y = cy_w - fp[1]

        pos[0] += delta_x
        pos[1] += delta_y
        fp[0] += delta_x
        fp[1] += delta_y

        camera.SetPosition(*pos)
        camera.SetFocalPoint(*fp)
        renderer.ResetCameraClippingRange()

        # Persist the new camera state
        self.save_camera_state(orientation)

        vtk_widget.GetRenderWindow().Render()


    def _fiji_zoom_at_cursor(self, vtk_widget, orientation, zoom_in=True, strength=1.0):
        """Zoom the 2D parallel-projection camera at the cursor (Fiji-style).

        strength scales the step (trackpad / high-res wheel). Linked MPR
        optionally mirrors the scale ratio to other panes.
        """
        import math

        renderer = getattr(self, f'{orientation}_renderer', None)
        if renderer is None:
            return
        camera = renderer.GetActiveCamera()
        if not camera.GetParallelProjection():
            return

        strength = max(0.15, min(float(strength), 3.0))
        base = 1.12  # ~12 % per notch (smoother than 15 %)
        zoom_factor = base ** strength

        interactor = vtk_widget.GetRenderWindow().GetInteractor()
        mx, my = interactor.GetEventPosition()

        coord = vtk.vtkCoordinate()
        coord.SetCoordinateSystemToDisplay()
        coord.SetValue(float(mx), float(my), 0.0)
        world_before = list(coord.GetComputedWorldValue(renderer))

        old_scale = float(camera.GetParallelScale())
        if zoom_in:
            new_scale = old_scale / zoom_factor
        else:
            new_scale = old_scale * zoom_factor

        s_min, s_max = self._mpr_zoom_limits(orientation)
        new_scale = max(s_min, min(new_scale, s_max))
        if abs(new_scale - old_scale) < 1e-9:
            return

        camera.SetParallelScale(new_scale)

        coord.SetValue(float(mx), float(my), 0.0)
        world_after = list(coord.GetComputedWorldValue(renderer))
        pos = list(camera.GetPosition())
        fp = list(camera.GetFocalPoint())
        for i in range(3):
            delta = world_before[i] - world_after[i]
            pos[i] += delta
            fp[i] += delta
        camera.SetPosition(*pos)
        camera.SetFocalPoint(*fp)

        renderer.ResetCameraClippingRange()
        self.save_camera_state(orientation)

        if self.volume_data is not None:
            h, w = self._mpr_image_size(orientation)
            self.add_ruler_overlay(renderer, orientation, (h, w))
        vtk_widget.GetRenderWindow().Render()

        # Optional linked zoom: same scale ratio on other panes (about crosshair)
        if getattr(self, "_mpr_link_nav", False) and old_scale > 1e-12:
            ratio = new_scale / old_scale
            for other in ("axial", "coronal", "sagittal"):
                if other == orientation:
                    continue
                o_ren = getattr(self, f"{other}_renderer", None)
                o_w = getattr(self, f"{other}_widget", None)
                if o_ren is None or o_w is None:
                    continue
                o_cam = o_ren.GetActiveCamera()
                if not o_cam.GetParallelProjection():
                    continue
                o_old = float(o_cam.GetParallelScale())
                o_min, o_max = self._mpr_zoom_limits(other)
                o_new = max(o_min, min(o_old * ratio, o_max))
                self._zoom_parallel_about_point(other, o_new, about_crosshair=True)


    def _mpr_default_parallel_scale(self, orientation):
        """Fit-to-view ParallelScale for this pane (half-height world units)."""
        h, w = self._mpr_image_size(orientation)
        vtk_widget = getattr(self, f"{orientation}_widget", None)
        if vtk_widget is None:
            return max(h, 1) * 0.5
        vp = vtk_widget.GetRenderWindow().GetSize()
        vp_w = max(float(vp[0]), 1.0)
        vp_h = max(float(vp[1]), 1.0)
        vp_aspect = vp_w / vp_h
        img_aspect = float(w) / max(float(h), 1.0)
        if img_aspect > vp_aspect:
            return (float(w) / vp_aspect) * 0.5
        return float(h) * 0.5


    def _mpr_image_size(self, orientation):
        """(h, w) of the displayed plane in voxels."""
        vol_z, vol_y, vol_x = self.volume_data.shape
        if orientation == "axial":
            return vol_y, vol_x
        if orientation == "coronal":
            return vol_z, vol_x
        return vol_y, vol_z  # sagittal


    def _mpr_pan_begin(self, orientation, pos):
        self._mpr_pan = {
            "ori": orientation,
            "last": QPoint(pos),
            "start_scale": None,
        }
        ren = getattr(self, f"{orientation}_renderer", None)
        if ren is not None:
            try:
                self._mpr_pan["start_scale"] = float(ren.GetActiveCamera().GetParallelScale())
            except Exception:
                pass
        self._set_mpr_cursor(orientation, Qt.ClosedHandCursor)


    def _mpr_pan_by_pixels(self, orientation, dx_px, dy_px):
        """Pan parallel camera by display-pixel deltas (Fiji-style)."""
        ren = getattr(self, f"{orientation}_renderer", None)
        widget = getattr(self, f"{orientation}_widget", None)
        if ren is None or widget is None:
            return
        cam = ren.GetActiveCamera()
        if not cam.GetParallelProjection():
            return
        size = widget.GetRenderWindow().GetSize()
        vp_h = max(float(size[1]), 1.0)
        scale = float(cam.GetParallelScale())
        # ParallelScale = half viewport height in world units
        world_per_px = (2.0 * scale) / vp_h
        # Qt Y down, VTK Y up
        dx_w = -dx_px * world_per_px
        dy_w = dy_px * world_per_px

        # Build camera right/up in world
        pos = list(cam.GetPosition())
        fp = list(cam.GetFocalPoint())
        up = list(cam.GetViewUp())
        view = [fp[0] - pos[0], fp[1] - pos[1], fp[2] - pos[2]]
        # right = view × up
        rx = view[1] * up[2] - view[2] * up[1]
        ry = view[2] * up[0] - view[0] * up[2]
        rz = view[0] * up[1] - view[1] * up[0]
        rn = (rx * rx + ry * ry + rz * rz) ** 0.5
        if rn < 1e-12:
            return
        rx, ry, rz = rx / rn, ry / rn, rz / rn
        un = (up[0] ** 2 + up[1] ** 2 + up[2] ** 2) ** 0.5
        if un < 1e-12:
            return
        ux, uy, uz = up[0] / un, up[1] / un, up[2] / un

        shift = [
            rx * dx_w + ux * dy_w,
            ry * dx_w + uy * dy_w,
            rz * dx_w + uz * dy_w,
        ]
        cam.SetPosition(pos[0] + shift[0], pos[1] + shift[1], pos[2] + shift[2])
        cam.SetFocalPoint(fp[0] + shift[0], fp[1] + shift[1], fp[2] + shift[2])
        ren.ResetCameraClippingRange()
        self.save_camera_state(orientation)
        widget.GetRenderWindow().Render()


    def _mpr_pan_end(self, orientation):
        self._mpr_pan = None
        # Restore hover cursor
        if self.crosshair_enabled:
            self._set_mpr_cursor(orientation, Qt.ArrowCursor)
        else:
            self._set_mpr_cursor(orientation, None)


    def _mpr_pan_move(self, orientation, pos):
        state = getattr(self, "_mpr_pan", None)
        if not state or state.get("ori") != orientation:
            return
        last = state["last"]
        dx_px = float(pos.x() - last.x())
        dy_px = float(pos.y() - last.y())
        state["last"] = QPoint(pos)
        if abs(dx_px) < 0.01 and abs(dy_px) < 0.01:
            return
        self._mpr_pan_by_pixels(orientation, dx_px, dy_px)
        if getattr(self, "_mpr_link_nav", False):
            for other in ("axial", "coronal", "sagittal"):
                if other != orientation:
                    self._mpr_pan_by_pixels(other, dx_px, dy_px)


    def _mpr_zoom_limits(self, orientation):
        """(s_min, s_max) — deep zoom (~few voxels in view) but not infinite out."""
        h, w = self._mpr_image_size(orientation)
        default = self._mpr_default_parallel_scale(orientation)
        # ParallelScale = half viewport height in voxels. Min ≈ 2 voxels half-height
        # (≈ 4 voxels visible vertically). Max ≈ 3× fit.
        s_min = 2.0
        s_max = max(default * 3.0, float(max(h, w)) * 1.5, s_min + 1.0)
        return s_min, s_max


    def _restore_interactor_style(self, orientation):
        """Restore the original VTK interactor style if it was swapped to dummy.

        This is a safety-net called from BOTH the Qt eventFilter AND the VTK
        observer release path.  It is idempotent — if the style was already
        restored (or was never swapped), this is a no-op.
        """
        if not hasattr(self, 'active_styles'):
            return
        saved = self.active_styles.pop(orientation, None)
        if saved is None:
            return
        widget = getattr(self, f'{orientation}_widget', None)
        if widget is None:
            return
        interactor = widget.GetRenderWindow().GetInteractor()
        # Only restore if we're currently on the dummy style
        if interactor.GetInteractorStyle() is getattr(self, '_dummy_style', None):
            interactor.SetInteractorStyle(saved)


    def _scroll_change_slice(self, orientation, delta):
        """Change the current slice index by *delta* for the given orientation.

        Used when Ctrl+scroll is pressed — allows navigating through the
        volume stack without a slider.
        """
        if self.volume_data is None:
            return

        vol_z, vol_y, vol_x = self.volume_data.shape
        newX, newY, newZ = self.crosshair_position

        if orientation == 'axial':
            max_idx = vol_z - 1
            newZ = max(0, min(newZ + delta, max_idx))
        elif orientation == 'coronal':
            max_idx = vol_y - 1
            newY = max(0, min(newY + delta, max_idx))
        else:  # sagittal
            max_idx = vol_x - 1
            newX = max(0, min(newX + delta, max_idx))

        self.updatePoint(newX, newY, newZ)


    def _set_mpr_cursor(self, orientation, cursor):
        widget = getattr(self, f"{orientation}_widget", None)
        if widget is None:
            return
        if cursor is None:
            widget.unsetCursor()
        else:
            widget.setCursor(cursor)


    def _set_mpr_one_to_one(self, orientation):
        """1 voxel ≈ 1 screen pixel (along viewport height)."""
        ren = getattr(self, f"{orientation}_renderer", None)
        widget = getattr(self, f"{orientation}_widget", None)
        if ren is None or widget is None or self.volume_data is None:
            return
        cam = ren.GetActiveCamera()
        if not cam.GetParallelProjection():
            return
        vp_h = max(float(widget.GetRenderWindow().GetSize()[1]), 1.0)
        # half-height in voxels for 1:1
        new_scale = vp_h * 0.5
        s_min, s_max = self._mpr_zoom_limits(orientation)
        new_scale = max(s_min, min(new_scale, s_max))
        # Zoom about crosshair (or image center)
        self._zoom_parallel_about_point(orientation, new_scale, about_crosshair=True)
        if getattr(self, "_mpr_link_nav", False):
            for other in ("axial", "coronal", "sagittal"):
                if other != orientation:
                    o_min, o_max = self._mpr_zoom_limits(other)
                    self._zoom_parallel_about_point(
                        other, max(o_min, min(new_scale, o_max)), about_crosshair=True
                    )


    def _shortcut_fit_active_pane(self):
        if self.volume_data is None:
            return
        self.reset_view(self._active_mpr_orientation())


    def _shortcut_one_to_one_active_pane(self):
        if self.volume_data is None:
            return
        self._set_mpr_one_to_one(self._active_mpr_orientation())


    def _shortcut_reset_active_pane(self):
        if self.volume_data is None:
            return
        active = getattr(self, "_active_grid_pane", None)
        # 3D pane: reset volume camera only (do not touch MPR / crosshair)
        if active == "view_3d":
            if hasattr(self, "reset_3d_view"):
                self.reset_3d_view()
            return
        ori = self._active_mpr_orientation()
        self.reset_view(ori)
        # Also re-center crosshair if enabled (full reset feel on MPR)
        if self.crosshair_enabled:
            self.reset_crosshair()


    def _toggle_link_mpr_nav(self, checked):
        self._mpr_link_nav = bool(checked)


    def _zoom_parallel_about_point(self, orientation, new_scale, about_crosshair=True):
        ren = getattr(self, f"{orientation}_renderer", None)
        widget = getattr(self, f"{orientation}_widget", None)
        if ren is None or widget is None:
            return
        cam = ren.GetActiveCamera()
        if not cam.GetParallelProjection():
            return
        # Anchor: crosshair world or current focal
        if about_crosshair and self.volume_data is not None:
            cx, cy, cz = self.crosshair_position
            if orientation == "axial":
                anchor = [float(cx), float(cy), float(cam.GetFocalPoint()[2])]
            elif orientation == "coronal":
                vol_z = self.volume_data.shape[0]
                anchor = [float(cx), float((vol_z - 1) - cz), float(cam.GetFocalPoint()[2])]
            else:
                anchor = [float(cz), float(cy), float(cam.GetFocalPoint()[2])]
        else:
            anchor = list(cam.GetFocalPoint())

        old_scale = float(cam.GetParallelScale())
        if old_scale <= 1e-12:
            old_scale = new_scale
        cam.SetParallelScale(float(new_scale))
        # Keep anchor fixed in display: shift by scale ratio around focal
        # (simple: move FP/pos so anchor stays — use display mapping)
        try:
            coord = vtk.vtkCoordinate()
            coord.SetCoordinateSystemToWorld()
            coord.SetValue(anchor[0], anchor[1], anchor[2])
            # After scale change without moving camera, re-pick is complex;
            # use parallel scale ratio on view plane offset from FP
            fp = list(cam.GetFocalPoint())
            pos = list(cam.GetPosition())
            # Offset of anchor from FP in world, scale by (1 - new/old) wait:
            # When parallel scale shrinks, world extent shrinks; to keep anchor
            # under same pixel, FP moves toward anchor.
            ratio = new_scale / old_scale
            # Camera space: FP' = anchor + (FP - anchor) * ratio
            nfp = [
                anchor[0] + (fp[0] - anchor[0]) * ratio,
                anchor[1] + (fp[1] - anchor[1]) * ratio,
                anchor[2] + (fp[2] - anchor[2]) * ratio,
            ]
            d = [nfp[0] - fp[0], nfp[1] - fp[1], nfp[2] - fp[2]]
            cam.SetFocalPoint(nfp[0], nfp[1], nfp[2])
            cam.SetPosition(pos[0] + d[0], pos[1] + d[1], pos[2] + d[2])
        except Exception:
            pass
        ren.ResetCameraClippingRange()
        self.save_camera_state(orientation)
        if self.volume_data is not None:
            h, w = self._mpr_image_size(orientation)
            self.add_ruler_overlay(ren, orientation, (h, w))
        widget.GetRenderWindow().Render()


