"""
Script to extract nav + crosshair method groups from viewer.py into mixin files.
Identifies method boundaries by indentation and creates:
  - inno3d/features/viewer/mpr_nav.py   (MprNavMixin)
  - inno3d/features/viewer/crosshair.py (CrosshairMixin)
Then patches viewer.py class declaration to inherit from them.

Run from project root:
  python scripts/extract_viewer_mixins.py
"""
import re
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VIEWER_PATH = PROJECT_ROOT / "inno3d" / "tabs" / "viewer.py"
NAV_OUT = PROJECT_ROOT / "inno3d" / "features" / "viewer" / "mpr_nav.py"
CROSSHAIR_OUT = PROJECT_ROOT / "inno3d" / "features" / "viewer" / "crosshair.py"

# ── Methods to extract into MprNavMixin ──────────────────────────────────────
NAV_METHODS = {
    "_restore_interactor_style",
    "_fiji_zoom_at_cursor",
    "_scroll_change_slice",
    "_ensure_crosshair_visible",
    "_toggle_link_mpr_nav",
    "_active_mpr_orientation",
    "_shortcut_fit_active_pane",
    "_shortcut_one_to_one_active_pane",
    "_shortcut_reset_active_pane",
    "_mpr_image_size",
    "_mpr_default_parallel_scale",
    "_mpr_zoom_limits",
    "_set_mpr_cursor",
    "_mpr_pan_begin",
    "_mpr_pan_move",
    "_mpr_pan_by_pixels",
    "_mpr_pan_end",
    "_set_mpr_one_to_one",
    "_zoom_parallel_about_point",
}

# ── Methods to extract into CrosshairMixin ───────────────────────────────────
CROSSHAIR_METHODS = {
    "reset_crosshair",
    "_crosshair_hit_radii",
    "_pick_world",
    "_pick_voxel",
    "_flush_crosshair_sync",
    "_crosshair_drag_update",
    "_crosshair_drag_end",
    "_cursor_for_crosshair_hit",
    "_crosshair_display_geometry",
    "toggle_crosshair",
    "updatePoint",
    "_sync_slice_sliders_from_crosshair",
    "update_2d_crosshair",
    "choose_crosshair_color",
}

METHOD_DEF_RE = re.compile(r"^    def (\w+)\(")


def parse_class_methods(lines):
    """Parse viewer.py: collect (method_name, start_line, end_line) for MultiPlanarView methods."""
    in_class = False
    methods = []  # (name, start_idx, end_idx)
    i = 0
    while i < len(lines):
        line = lines[i]
        # Detect start of MultiPlanarView class
        if line.startswith("class MultiPlanarView"):
            in_class = True
        if not in_class:
            i += 1
            continue
        m = METHOD_DEF_RE.match(line)
        if m:
            name = m.group(1)
            start = i
            # Find next method at same or shallower indent (4-space indent)
            j = i + 1
            while j < len(lines):
                nxt = lines[j]
                # Next method or class definition at depth 4
                if (nxt.startswith("    def ") or nxt.startswith("class ")) and j > i + 1:
                    break
                j += 1
            methods.append((name, start, j))
            i = j
        else:
            i += 1
    return methods


def build_mixin_header(class_name):
    return f'''"""Extracted mixin — part of inno3d.features.viewer refactor.

This module is auto-generated by scripts/extract_viewer_mixins.py.
Do NOT edit manually; edit viewer.py then re-run the script.

Layer: features/viewer (imports Qt, VTK — not for domain/infra use).
"""
from __future__ import annotations
# Qt / VTK imports are inherited from the host class at runtime.
# This mixin uses only `self.*` — no standalone imports needed here.


class {class_name}:
    """Mixin providing {class_name.replace("Mixin", "")} behaviour for MultiPlanarView.

    All methods use ``self.*`` attributes owned by MultiPlanarView.
    Do not instantiate directly.
    """
'''


def main():
    print(f"Reading {VIEWER_PATH} ...")
    lines = VIEWER_PATH.read_text(encoding="utf-8").splitlines(keepends=True)
    methods = parse_class_methods(lines)
    name_to_range = {n: (s, e) for n, s, e in methods}

    print(f"Found {len(methods)} methods in MultiPlanarView")

    # Build nav mixin
    nav_body = build_mixin_header("MprNavMixin")
    missing_nav = []
    for mname in sorted(NAV_METHODS):
        if mname not in name_to_range:
            missing_nav.append(mname)
            continue
        s, e = name_to_range[mname]
        nav_body += "".join(lines[s:e]) + "\n"
    if missing_nav:
        print(f"WARNING — MprNav: methods not found: {missing_nav}")
    NAV_OUT.write_text(nav_body, encoding="utf-8")
    print(f"Wrote {NAV_OUT} ({nav_body.count(chr(10))} lines)")

    # Build crosshair mixin
    ch_body = build_mixin_header("CrosshairMixin")
    missing_ch = []
    for mname in sorted(CROSSHAIR_METHODS):
        if mname not in name_to_range:
            missing_ch.append(mname)
            continue
        s, e = name_to_range[mname]
        ch_body += "".join(lines[s:e]) + "\n"
    if missing_ch:
        print(f"WARNING — Crosshair: methods not found: {missing_ch}")
    CROSSHAIR_OUT.write_text(ch_body, encoding="utf-8")
    print(f"Wrote {CROSSHAIR_OUT} ({ch_body.count(chr(10))} lines)")

    # Verify extracted methods exist in output
    nav_text = NAV_OUT.read_text(encoding="utf-8")
    ch_text = CROSSHAIR_OUT.read_text(encoding="utf-8")
    nav_ok = sum(1 for n in NAV_METHODS if f"def {n}(" in nav_text)
    ch_ok = sum(1 for n in CROSSHAIR_METHODS if f"def {n}(" in ch_text)
    print(f"MprNavMixin:    {nav_ok}/{len(NAV_METHODS)} methods present")
    print(f"CrosshairMixin: {ch_ok}/{len(CROSSHAIR_METHODS)} methods present")

    print("\nDone. Next step: update MultiPlanarView(QWidget) → MultiPlanarView(MprNavMixin, CrosshairMixin, QWidget)")


if __name__ == "__main__":
    main()
